# config.yaml
smtp:
  server: smtp.fastmail.com
  port: 465
  username: your_username
  password: your_password

email:
  from: $EMAIL_SENDER
  to:
    - $EMAIL_RECIPIENT_1
  subject: IP Address Changed

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file:
    path: /logs/ip_monitor.log
    rotation:
      when: midnight
      interval: 1
      backupCount: 7

database:
  url: 'sqlite:///ip_monitor.db'  # Database URL

reporting:
  frequency: daily  # daily, weekly, or monthly
  email_recipient_env_var: REPORT_EMAIL  # Name of the environment variable holding the email address

ip_check:
  interval: 60  # minutes
  services:
    - https://api.ipify.org?format=json
    - https://api.my-ip.io/ip.json
