version: '3.1'
services:
  ip-monitor:
    container_name: ip_monitor  # Specify container name
    image: ip_monitor-image     # Specify image name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./logs:/logs  # map logs directory in container to a local directory
    environment:
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - EMAIL_RECIPIENT
    env_file:
      - .env
